import React from 'react';
import { useNavigate } from 'react-router-dom';

const WelcomeScreen = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-gray-900">
      <div className="max-w-2xl w-full">
        <div className="text-center mb-8">
          <h1 className="text-5xl font-bold text-indigo-500 mb-4">
            AI Quiz Master
          </h1>
          <p className="text-xl text-gray-300">
            Challenge your knowledge with AI-powered questions
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 shadow-lg hover:shadow-indigo-500/25 transition-shadow duration-300 animate-slide-up" 
               style={{ animationDelay: '0.01s' }}>
            <div className="flex items-center space-x-4">
              <div className="p-3 bg-indigo-600/20 rounded-lg">
                <svg className="w-6 h-6 text-indigo-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white mb-1">AI-Powered</h3>
                <p className="text-gray-400 text-sm">
                  Dynamic questions generated by advanced AI
                </p>
              </div>
            </div>
          </div>

          <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 shadow-lg hover:shadow-pink-500/25 transition-shadow duration-300 animate-slide-up"
               style={{ animationDelay: '0.01s' }}>
            <div className="flex items-center space-x-4">
              <div className="p-3 bg-pink-600/20 rounded-lg">
                <svg className="w-6 h-6 text-pink-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                </svg>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white mb-1">12 Categories</h3>
                <p className="text-gray-400 text-sm">
                  Wide range of topics to test your knowledge
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row justify-center gap-4">
          <button 
            onClick={() => navigate('/setup')}
            className="px-6 py-2.5 bg-indigo-500 text-white font-medium rounded-lg
                     hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 
                     focus:ring-offset-2 focus:ring-offset-gray-900 transition-all duration-200"
          >
            Start Quiz
          </button>
          <button 
            onClick={() => navigate('/leaderboard')}
            className="px-6 py-2.5 border-2 border-gray-700 text-gray-300 font-medium rounded-lg
                     hover:bg-gray-300/10 focus:outline-none focus:ring-2 focus:ring-gray-300/50
                     focus:ring-offset-2 focus:ring-offset-gray-900 transition-all duration-200"
          >
            Leaderboard
          </button>
        </div>
      </div>
    </div>
  );
};

export default WelcomeScreen;
